export const TOGGLE_FAV_MOVIE = 'TOGGLE_FAV_MOVIE';
export const TOGGLE_FAV_MOVIE_START = 'TOGGLE_FAV_MOVIE_START';
export const FETCH_MOVIES_START = 'FETCH_MOVIES_START';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILED = 'FETCH_MOVIES_FAILED';
export const FETCH_MOVIES = 'FETCH_MOVIES';